name = "streamq"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "streamq-db"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"
